#!/usr/bin/env node
/**
 * vendor-primer.mjs — Vendor @primer/primitives CSS token files and @primer/octicons SVGs.
 * Run: npm run vendor:primer
 * Output: assets/css/primer/*.css, assets/css/primer/primer.css, scripts/icons.py, assets/js/icons.js
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PRIMER_DIR = join(ROOT, 'assets', 'css', 'primer');
const PKG = JSON.parse(
  readFileSync(join(ROOT, 'node_modules', '@primer', 'primitives', 'package.json'), 'utf8')
);
const DIST = join(ROOT, 'node_modules', '@primer', 'primitives', 'dist', 'css');
const OCTICONS_DATA = JSON.parse(
  readFileSync(join(ROOT, 'node_modules', '@primer', 'octicons', 'build', 'data.json'), 'utf8')
);

const VERSION = PKG.version;
const HEADER = `/* vendored from @primer/primitives v${VERSION} — do not edit; run npm run vendor:primer */\n`;

// Source → destination mapping
const FILES = {
  'base/size/size.css': 'base-size.css',
  'base/typography/typography.css': 'base-typography.css',
  'functional/size/size.css': 'size.css',
  'functional/size/border.css': 'border.css',
  'functional/size/breakpoints.css': 'breakpoints.css',
  'functional/typography/typography.css': 'typography.css',
  'functional/motion/motion.css': 'motion.css',
  'functional/themes/light.css': 'theme-light.css',
  'functional/themes/dark.css': 'theme-dark.css',
  'functional/themes/dark-dimmed.css': 'theme-dark-dimmed.css',
  'functional/themes/light-high-contrast.css': 'theme-light-hc.css',
  'functional/themes/dark-high-contrast.css': 'theme-dark-hc.css',
};

// Order for concatenation (base first, then functional, themes last)
const CONCAT_ORDER = [
  'base-size.css',
  'base-typography.css',
  'size.css',
  'border.css',
  'breakpoints.css',
  'typography.css',
  'motion.css',
  'theme-light.css',
  'theme-dark.css',
  'theme-dark-dimmed.css',
  'theme-light-hc.css',
  'theme-dark-hc.css',
];

// Octicon whitelist (name → used sizes)
const ICON_WHITELIST = {
  home: [16],
  briefcase: [16],
  code: [16],
  file: [16],
  calendar: [16],
  location: [16],
  mail: [16],
  'mark-github': [16],
  sun: [16],
  moon: [16],
  'device-desktop': [16],
  check: [16],
  'chevron-down': [16],
  'link-external': [16],
  search: [16],
  organization: [16],
  rocket: [16],
  trophy: [16],
  info: [16],
  eye: [16],
  download: [16],
  x: [16],
  clock: [16],
  alert: [24],
  'shield-check': [24],
  sync: [16],
  tools: [16],
  checklist: [16],
  comment: [16],
  'paper-airplane': [16],
  rss: [16],
  log: [16],
};
// LinkedIn has no octicon — we vendor a simple-icons inline path
const LINKEDIN_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>';

// --- 1. Copy and prepend headers ---
mkdirSync(PRIMER_DIR, { recursive: true });

for (const [src, dest] of Object.entries(FILES)) {
  const srcPath = join(DIST, src);
  const content = readFileSync(srcPath, 'utf8');
  writeFileSync(join(PRIMER_DIR, dest), HEADER + content);
}

// --- 2. Concatenate primer.css ---
let concat = `/* primer.css — concatenated Primer primitives v${VERSION} */\n`;
concat += `/* Do not edit; run npm run vendor:primer */\n\n`;
for (const name of CONCAT_ORDER) {
  concat += readFileSync(join(PRIMER_DIR, name), 'utf8') + '\n';
}
writeFileSync(join(PRIMER_DIR, 'primer.css'), concat);

// --- 3. Generate icons.py ---
function indent(s, n) {
  const pad = ' '.repeat(n);
  return s
    .split('\n')
    .map((l) => (l ? pad + l : l))
    .join('\n');
}

let py = `#!/usr/bin/env python3
"""Octicon SVGs for server-side HTML generation. Auto-generated by vendor-primer.mjs — do not edit."""
ICONS = {}
`;

// Add each icon
for (const [name, sizes] of Object.entries(ICON_WHITELIST)) {
  const icon = OCTICONS_DATA[name];
  for (const size of sizes) {
    const h = icon.heights[String(size)];
    if (!h) continue;
    const key = `${name.toUpperCase().replace(/-/g, '_')}_${size}`;
    const svg = `<svg class="octicon octicon-${name}" xmlns="http://www.w3.org/2000/svg" width="${h.width}" height="${size}" viewBox="0 0 ${h.width} ${size}" aria-hidden="true" focusable="false" fill="currentColor">${h.path}</svg>`;
    py += `ICONS["${key}"] = '''${svg}'''\n`;
  }
}

// LinkedIn special case
py += `ICONS["LINKEDIN_16"] = '''<svg class="octicon octicon-linkedin" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>'''\n`;

writeFileSync(join(ROOT, 'scripts', 'icons.py'), py);

// --- 4. Generate icons.js ---
let js = `// Octicon SVGs for client-side rendering. Auto-generated by vendor-primer.mjs — do not edit.
const OCTICONS = {};
`;

for (const [name, sizes] of Object.entries(ICON_WHITELIST)) {
  const icon = OCTICONS_DATA[name];
  for (const size of sizes) {
    const h = icon.heights[String(size)];
    if (!h) continue;
    const key = `${name.toUpperCase().replace(/-/g, '_')}_${size}`;
    const svg = `<svg class="octicon octicon-${name}" xmlns="http://www.w3.org/2000/svg" width="${h.width}" height="${size}" viewBox="0 0 ${h.width} ${size}" aria-hidden="true" focusable="false" fill="currentColor">${h.path}</svg>`;
    js += `OCTICONS["${key}"] = '${svg}';\n`;
  }
}

js += `OCTICONS["LINKEDIN_16"] = '<svg class="octicon octicon-linkedin" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>';\n`;

js += `
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { OCTICONS };
}
`;

writeFileSync(join(ROOT, 'assets', 'js', 'icons.js'), js);

// --- 5. README ---
const readme = `# Primer Design Tokens (vendored)

Vendored from \`@primer/primitives\` v${VERSION}.

## Files

| File | Source |
|------|--------|
${CONCAT_ORDER.map((f) => `| ${f} | \`@primer/primitives/dist/css/${Object.entries(FILES).find(([, d]) => d === f)?.[0]}\` |`).join('\n')}
| **primer.css** | concatenation of all above, in order |

## Update procedure

\`\`\`bash
# 1. Bump version in package.json
npm install --save-dev @primer/primitives@latest

# 2. Re-vendor
npm run vendor:primer

# 3. Review diff, commit
git add assets/css/primer/ scripts/icons.py assets/js/icons.js
git commit -m "chore: vendor @primer/primitives vX.Y.Z"
\`\`\`

## Do not edit

All files in this directory are auto-generated. Edit \`scripts/vendor-primer.mjs\` to change the vendoring logic, then re-run.
`;

writeFileSync(join(PRIMER_DIR, 'README.md'), readme);

console.log(`✅ Vendored @primer/primitives v${VERSION}`);
console.log(`   → ${CONCAT_ORDER.length} token files + primer.css concatenated`);
console.log(
  `✅ Generated scripts/icons.py (${Object.keys(ICON_WHITELIST).length} icons + linkedin)`
);
console.log(`✅ Generated assets/js/icons.js`);
console.log(`✅ Wrote assets/css/primer/README.md`);
