- generic [active] [ref=e1]:
  - link "← Portfolio" [ref=e3] [cursor=pointer]:
    - /url: https://agreddy.com
  - main [ref=e4]:
    - heading "Network Speed Test" [level=1] [ref=e5]
    - text: Test length
    - combobox "Test length" [ref=e6]:
      - option "Auto" [selected]
      - option "10s"
      - option "20s"
      - option "30s"
    - button "Start Test" [ref=e7] [cursor=pointer]
    - paragraph [ref=e8]: Idle
    - img [ref=e9]:
      - generic [ref=e12]: "0"
      - generic [ref=e13]: "100"
      - generic [ref=e14]: "200"
      - generic [ref=e15]: Mbps
    - paragraph [ref=e16]
    - generic [ref=e18]:
      - generic [ref=e19]: Download
      - generic [ref=e21]: Upload
  - contentinfo [ref=e23]:
    - link "View source on GitHub" [ref=e24] [cursor=pointer]:
      - /url: https://github.com/agopalareddy/speedtest